spring:
      application:
               name: comments-demo
server:
      port: 9000

graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: true

graphiql:
      mapping: /graphiql
      endpoint: /graphql
      enabled: true
      pageTitle: GraphiQL
